### ISSUE TITLE
IndexMissingException[[test] missing

### ISSUE THREAD

**Issue by bx5974** [kzwang/elasticsearch-image#2]
[elasticsearch-1.2.2]$ curl -XPUT 'localhost:9201/test/test/_mapping' -d '{

> ```
> "test": {
>     "properties": {
>         "my_img": {
>             "type": "image",
>             "feature": {
>                 "CEDD": {
>                     "hash": "BIT_SAMPLING"
>                 },
>                 "JCD": {
>                     "hash": ["BIT_SAMPLING", "LSH"]
>                 },
>                 "FCTH": {}
>             },
>             "metadata": {
>                 "jpeg.image_width": {
>                     "type": "string",
>                     "store": "yes"
>                 },
>                 "jpeg.image_height": {
>                     "type": "string",
>                     "store": "yes"
>                 }
>             }
>         }
>     }
> }
> ```
> 
> }'
> {"error":"IndexMissingException[[test] missing]","status":404}

please let me know, how do we solve this issue?

**Comment by se7en007** [comment]
This command creates a mapping in index test "localhost:9201/test/test/_mapping". You have to first create your test index.
