### ISSUE TITLE
Building for other elasticsearch versions?

### ISSUE THREAD

**Issue by nickstanisha** [kzwang/elasticsearch-image#24]
Are there any instructions for building these plugins for other versions of Elasticsearch? @kzwang 's version seems to have stopped at 1.1, and @jmoati 's version stops at 2.1.1. Is there a reason for such specific compatibility, or can this same code be built for other versions of Elasticsearch?

**Comment by kiwionly** [comment]
https://github.com/kiwionly/elasticsearch-image

**Comment by nickstanisha** [comment]
I'm not following... I see that this repository supports more versions, but what I'm looking for is a set of instructions for building the plugin with an arbitrary X.Y.Z version. 

It seems weird to me that this project has so many forks, with each fork supporting a different set of Elasticsearch versions. Does the source code really have to change for every +0.0.1 Elasticsearch release? Why not have a single repository containing instructions for building the plugin for an arbitrary Elasticsearch version?

**Comment by nickstanisha** [comment]
Alternatively, is each plugin backwards compatible? I don't need build instructions for any Elasticsearch version if I know that the newest one will always work.

**Comment by kiwionly** [comment]
Code change is because of code/libraries changed in E.S in difference version.

mean you need to build particular version for particular version of E.S.

Original code no longer maintainer, hence that are plenty of fork try to support the version developer own need.

**Comment by nickstanisha** [comment]
Hmmm.. alright. Thanks for your response and for continuing work on this project!
